### ISSUE TITLE
Muavic Dataset

### ISSUE THREAD

**Issue by longkhanh-fam** [roudimit/whisper-flamingo#2]
Hi @roudimit  ,
In muavic repo, I ran get_data.py without any modifications, but while the mted folder contains full-screen videos as expected, the output folders are only generating black screen videos rather than cropped mouth regions.
I just wonder the face detection/alignment might be failing. I’ve tested this with "ar" and "de" languages, and the issue persists for both.
Can you help me to fix it.
Thank you!

**Comment by roudimit** [comment]
Hi @longkhanh-fam, thanks for your interest. I'm not sure what the issue is since I didn't experience that problem when processing muavic. The main functions responsible for data processing is [`preprocess_mtedx_video`](https://github.com/facebookresearch/muavic/blob/12f7f09c8b28f1af4285c1e4f2c66f6c82c86af6/mtedx_utils.py#L158). [Here](https://www.dropbox.com/scl/fo/zp79btpe615z699slf9rc/AL3lrhdLu24wKw5jnp7gcjY?rlkey=r08i65r5ewr3jxe8qarsp32xl&st=jiz0zm8p&dl=0) is the cropped video and face landmark detection metadata for video `muavic/de/video/test/r2tvb4-i4EE/r2tvb4-i4EE_0000.mp4` (the metadata path is `metadata/de/test/r2tvb4-i4EE.pkl`). Since you were able to download the original video, can you try running this function on this one example and try to see when it goes wrong? 

Also, how long is the black video (does it match the length of the audio), and what is the dimension? It seems weird because even if the facial landmarks metadata are missing, then the [original video would be resized](https://github.com/facebookresearch/muavic/blob/12f7f09c8b28f1af4285c1e4f2c66f6c82c86af6/mtedx_utils.py#L151) to 96 by 96. My guess is something is wrong with the video loading.

**Comment by longkhanh-fam** [comment]
Thank you @roudimit for kindly provide the cropped video and the metadata path. 
I have checked the length and the dimension of the video. I notice that the the length of the video match that of audio, and the dimension is also 96x96. Actually, I think the output cropped video is cropped with the wrong region, as the it shown another region of the video, not the mouth one.

I re-run again with your provided file and in [here](https://github.com/facebookresearch/muavic/blob/12f7f09c8b28f1af4285c1e4f2c66f6c82c86af6/mtedx_utils.py#L151) , it does go to the crop_patch function, but wrong region is cropped.

**Comment by sungnyun** [comment]
I'm experiencing the same problem with @longkhanh-fam. My cropped video for de/video/test/r2tvb4-i4EE shows the same background view as his.

**Comment by sungnyun** [comment]
Check this [comment](https://github.com/facebookresearch/muavic/issues/23#issuecomment-2449404531)
